name: Build Linux-g14 Arch Kernel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up yay (AUR helper)
      run: |
        git clone https://aur.archlinux.org/yay.git
        cd yay
        makepkg -si --noconfirm

    - name: Install build dependencies
      run: |
        yay -S --needed --noconfirm base-devel
        yay -S --needed --noconfirm linux-headers

    - name: Add CONFIG_ANDROID options to prepare()
      run: |
        cd ${{ github.workspace }}
        bash add_lines.sh

    - name: Configure and build kernel
      run: |
        cd ${{ github.workspace }}
        makepkg -s --noconfirm
        echo "==============="
        echo "Package created:"
        echo `ls *.pkg.tar.zst`
        echo "==============="
