name: Build Linux-g14 Arch Kernel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true

    - name: Build Arch Linux kernel in Docker
      run: |
        docker pull archlinux/base
        docker run -v ${{ github.workspace }}:/pkg archlinux/base /bin/bash -c '
          pacman -Sy --noconfirm devtools base-devel linux-headers # Install build dependencies
          cd /tmp
          git clone https://aur.archlinux.org/linux-g14.git
          cd linux-g14
          cp /pkg/add_lines.sh ./
          bash add_lines.sh
          makepkg -s --noconfirm
        '

    - name: Move package to workspace
      run: |
        mkdir ${{ github.workspace }}/pkg
        mv /tmp/linux-g14/*.pkg.tar.zst ${{ github.workspace }}/pkg/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-g14-kernel
        path: ${{ github.workspace }}/pkg/*.pkg.tar.zst
